USE [master]
GO

/****** Object:  Database [DB_GranaCurta]    Script Date: 05/06/2018 01:38:21 ******/
CREATE DATABASE [DB_GranaCurta]
	CONTAINMENT = NONE
	ON  PRIMARY (
		NAME = N'DB_GranaCurta',
		FILENAME =
			--Local
			--N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_GranaCurta.mdf',
			--AMZ RDS
			N'D:\RDSDBDATA\DATA\DB_GranaCurta.mdf',
		SIZE = 8192KB ,
		MAXSIZE = UNLIMITED,
		FILEGROWTH = 65536KB
	)
	LOG ON (
		NAME = N'DB_GranaCurta_log',
		FILENAME =
			--Local
			--N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_GranaCurta_log.ldf' ,
			--AMZ RDS
			N'D:\RDSDBDATA\DATA\DB_GranaCurta_log.ldf' ,
		SIZE = 8192KB ,
		MAXSIZE = 2048GB ,
		FILEGROWTH = 65536KB
	)
	COLLATE SQL_Latin1_General_CP1_CI_AS
GO

ALTER DATABASE [DB_GranaCurta] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_GranaCurta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_GranaCurta] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_GranaCurta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_GranaCurta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_GranaCurta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

--ALTER DATABASE [DB_GranaCurta] SET TRUSTWORTHY OFF 
--GO

ALTER DATABASE [DB_GranaCurta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_GranaCurta] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_GranaCurta] SET READ_COMMITTED_SNAPSHOT OFF 
GO

--ALTER DATABASE [DB_GranaCurta] SET HONOR_BROKER_PRIORITY OFF 
--GO

ALTER DATABASE [DB_GranaCurta] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_GranaCurta] SET  MULTI_USER 
GO

ALTER DATABASE [DB_GranaCurta] SET PAGE_VERIFY CHECKSUM  
GO

--ALTER DATABASE [DB_GranaCurta] SET DB_CHAINING OFF 
--GO

ALTER DATABASE [DB_GranaCurta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_GranaCurta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_GranaCurta] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_GranaCurta] SET QUERY_STORE = OFF
GO

USE [DB_GranaCurta]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DB_GranaCurta] SET  READ_WRITE 
GO


